inputFile: participants_snowcamp-2020.csv
univsFile: participants_ateliers_snowcamp-2020.csv
outputDirectory: target

badge:
  colors:
    attendee: "#FFF20C"
    speaker: "#A9B2FF"
    sponsor: "#4DCA2C"
    staff: "#ee0000"
