inputFile: participants_snowcamp-2022.csv
univsFile: participants_ateliers_snowcamp-2022.csv
outputDirectory: target

badge:
  colors:
    attendee: "#3FC633"
    speaker: "#FEAF00"
    sponsor: "#E51AE2"
    staff: "#ee0000"
